
PongController: src/controller/*.java src/model/*.java src/view/*.java
	javac -d bin src/controller/*.java src/model/*.java src/view/*.java -classpath bin
	echo To run use: java -cp bin controller.PongController

all:
	javac -d bin src/controller/*.java src/model/*.java src/view/*.java -classpath bin
